spring:
  application:
    name: shop-user #服务名
  profiles: 8762
  zipkin:
    base-url:http://localhost:9411
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://registry-server-1:7777/eureka/
management:
  health:
    refresh:
      enabled: false
  port: 54002